import '../models/stress_location.dart';

const mockStressLocations = <StressLocation>[
  StressLocation(
    id: 'nyc-midtown',
    name: 'Midtown Manhattan',
    latitude: 40.7549,
    longitude: -73.9840,
    populationDensity: 92,
    airQualityIndex: 68,
    noiseLevel: 88,
    costOfLivingIndex: 94,
    trafficIndex: 91,
    safetyIndex: 58,
    stressScore: 0,
  ),
  StressLocation(
    id: 'brooklyn-heights',
    name: 'Brooklyn Heights',
    latitude: 40.6960,
    longitude: -73.9933,
    populationDensity: 73,
    airQualityIndex: 52,
    noiseLevel: 58,
    costOfLivingIndex: 82,
    trafficIndex: 64,
    safetyIndex: 76,
    stressScore: 0,
  ),
  StressLocation(
    id: 'jersey-city',
    name: 'Jersey City Waterfront',
    latitude: 40.7178,
    longitude: -74.0431,
    populationDensity: 67,
    airQualityIndex: 55,
    noiseLevel: 61,
    costOfLivingIndex: 74,
    trafficIndex: 69,
    safetyIndex: 71,
    stressScore: 0,
  ),
  StressLocation(
    id: 'central-park',
    name: 'Central Park North',
    latitude: 40.8007,
    longitude: -73.9580,
    populationDensity: 48,
    airQualityIndex: 38,
    noiseLevel: 34,
    costOfLivingIndex: 76,
    trafficIndex: 43,
    safetyIndex: 81,
    stressScore: 0,
  ),
  StressLocation(
    id: 'newark-downtown',
    name: 'Downtown Newark',
    latitude: 40.7357,
    longitude: -74.1724,
    populationDensity: 71,
    airQualityIndex: 72,
    noiseLevel: 70,
    costOfLivingIndex: 62,
    trafficIndex: 77,
    safetyIndex: 46,
    stressScore: 0,
  ),
  StressLocation(
    id: 'long-island-city',
    name: 'Long Island City',
    latitude: 40.7447,
    longitude: -73.9485,
    populationDensity: 76,
    airQualityIndex: 61,
    noiseLevel: 74,
    costOfLivingIndex: 83,
    trafficIndex: 72,
    safetyIndex: 69,
    stressScore: 0,
  ),
];
